[tool.poetry]
name = "combine"
version = "0.1.0"
description = ""
authors = ["Andre van Zuydam <andrevanzuydam@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
tina4-python = "^0.2.46"
mysql-connector-python = "^9.1.0"
redis = "^5.2.1"
pika = "^1.3.2"
poetry-plugin-export = "^1.9.0"


[tool.poetry.group.dev.dependencies]
poetry-plugin-export = "^1.9.0"
jurigged = "^0.6.0"

[tool.poetry.requires-plugins]
poetry-plugin-export = ">=1.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
