[project]
name = "combine"
version = "0.1.0"
description = ""
authors = [
    {name = "Andre van Zuydam",email = "andrevanzuydam@gmail.com"}
]
package-mode = false
readme = "README.md"
requires-python = "^3.10"
dependencies = [
    "tina4-python (>=0.2.43,<0.3.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


