insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (1,'James Pearce Jr.','','Football', 'Tennessee','EDGE','6''4"','242','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (2,'Luther Burden III','','Football', 'Missouri','WR','5''11"','208','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (3,'Will Campbell','','Football', 'LSU','OT','6''6"','325','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (4,'Carson Beck','','Football', 'Georgia','QB','6''4"','220','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (5,'Will Johnson','','Football', 'Michigan','CB','6''2"','202','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (6,'Jalen Milroe','','Football', 'Alabama','QB','6''2"','220','RJR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (7,'Kelvin Banks Jr.','','Football', 'Texas','OT','6''4"','324','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (8,'Shedeur Sanders','','Football', 'Colorado','QB','6''2"','215','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (9,'Mason Graham','','Football', 'Michigan','DL3T','6''3"','318','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (10,'Travis Hunter','','Football', 'Colorado','CB','6''1"','185','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (11,'Tetairoa McMillan','','Football', 'Arizona','WR','6''4"','210','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (12,'Drew Allar','','Football', 'Penn State','QB','6''5"','242','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (13,'Malaki Starks','','Football', 'Georgia','S','6''1"','205','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (14,'Benjamin Morrison','','Football', 'Notre Dame','CB','6''0"','185','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (15,'Harold Perkins Jr.','','Football', 'LSU','OLB','6''2"','220','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (16,'Emeka Egbuka','','Football', 'Ohio State','WR','6''1"','205','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (17,'Deone Walker','','Football', 'Kentucky','DL1T','6''5"','348','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (18,'Evan Stewart','','Football', 'Oregon','WR','5''11"','175','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (19,'J.T. Tuimoloau','','Football', 'Ohio State','EDGE','6''4"','270','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (20,'Emery Jones','','Football', 'LSU','OT','6''5"','315','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (21,'Isaiah Bond','','Football', 'Texas','WR','5''11"','182','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (22,'Denzel Burke','','Football', 'Ohio State','CB','6''1"','190','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (23,'Nic Scourton','','Football', 'Texas A&M','DL5T','6''4"','280','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (24,'Kenneth Grant','','Football', 'Michigan','DL1T','6''3"','339','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (25,'Barrett Carter','','Football', 'Clemson','OLB','6''1"','225','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (26,'Quinn Ewers','','Football', 'Texas','QB','6''2"','207','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (27,'Dani Dennis-Sutton','','Football', 'Penn State','EDGE','6''4"','261','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (28,'Tyleik Williams','','Football', 'Ohio State','DL1T','6''3"','318','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (29,'Princely Umanmielen','','Football', 'Ole Miss','EDGE','6''4"','245','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (30,'TreVeyon Henderson','','Football', 'Ohio State','RB','5''10"','214','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (31,'Patrick Payton','','Football', 'Florida State','EDGE','6''5"','239','RJR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (32,'Tacario Davis','','Football', 'Arizona','CB','6''4"','195','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (33,'Conner Weigman','','Football', 'Texas A&M','QB','6''3"','215','RSO');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (34,'Jack Sawyer','','Football', 'Ohio State','EDGE','6''4"','267','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (35,'Josh Simmons','','Football', 'Ohio State','OT','6''5"','310','RJR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (36,'Colston Loveland','','Football', 'Michigan','TE','6''5"','245','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (37,'Davison Igbinosun','','Football', 'Ohio State','CB','6''1"','190','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (38,'Wyatt Milum','','Football', 'West Virginia','OT','6''6"','312','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (39,'Dasan McCullough','','Football', 'Oklahoma','OLB','6''4"','227','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (40,'Rod Moore','','Football', 'Michigan','S','6''0"','185','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (41,'Landon Jackson','','Football', 'Arkansas','DL5T','6''7"','280','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (42,'Tyler Booker','','Football', 'Alabama','OG','6''5"','332','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (43,'Walter Nolen','','Football', 'Ole Miss','DL3T','6''4"','290','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (44,'Mykel Williams','','Football', 'Georgia','EDGE','6''4"','265','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (45,'Maxwell Hairston','','Football', 'Kentucky','CB','6''1"','181','RJR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (46,'Luke Lachey','','Football', 'Iowa','TE','6''6"','253','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (47,'Dontay Corleone','','Football', 'Cincinnati','DL1T','6''2"','320','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (48,'Abdul Carter','','Football', 'Penn State','OLB','6''2"','249','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (49,'Tate Ratledge','','Football', 'Georgia','OG','6''5"','315','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (50,'Ollie Gordon II','','Football', 'Oklahoma State','RB','6''1"','211','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (51,'Danny Stutsman','','Football', 'Oklahoma','ILB','6''3"','240','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (52,'Jonah Savaiinaea','','Football', 'Arizona','OG','6''5"','330','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (53,'Xavier Nwankpa','','Football', 'Iowa','S','6''2"','210','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (54,'Nazir Stackhouse','','Football', 'Georgia','DL1T','6''3"','320','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (55,'Howard Cross III','','Football', 'Notre Dame','DL3T','6''1"','288','GR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (56,'Nick Singleton','','Football', 'Penn State','RB','6''0"','222','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (57,'Nick Emmanwori','','Football', 'South Carolina','S','6''3"','220','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (58,'Blake Miller','','Football', 'Clemson','OT','6''5"','310','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (59,'Antwane Wells Jr.','','Football', 'Ole Miss','WR','6''1"','207','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (60,'R.J. Oben','','Football', 'Notre Dame','EDGE','6''4"','260','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (61,'Sebastian Castro','','Football', 'Iowa','CBN','5''11"','205','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (62,'Sonny Styles','','Football', 'Ohio State','OLB','6''3"','230','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (63,'Oscar Delp','','Football', 'Georgia','TE','6''5"','245','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (64,'Tory Horton','','Football', 'Colorado State','WR','6''1"','180','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (65,'Domani Jackson','','Football', 'Alabama','CB','6''1"','190','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (66,'Jaheim Oatis','','Football', 'Alabama','DL1T','6''5"','320','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (67,'Parker Brailsford','','Football', 'Alabama','OC','6''2"','275','RSO');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (68,'Andrew Mukuba','','Football', 'Texas','S','6''0"','185','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (69,'Jonah Monheim','','Football', 'USC','OT','6''5"','295','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (70,'Quinshon Judkins','','Football', 'Ohio State','RB','5''10"','210','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (71,'Smael Mondon Jr.','','Football', 'Georgia','OLB','6''3"','220','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (72,'Jaxson Dart','','Football', 'Ole Miss','QB','6''2"','220','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (73,'Bear Alexander','','Football', 'USC','DL3T','6''3"','300','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (74,'D.J. Campbell','','Football', 'Texas','OG','6''3"','343','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (75,'David Bailey','','Football', 'Stanford','EDGE','6''3"','240','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (76,'Dorian Strong','','Football', 'Virginia Tech','CB','6''0"','182','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (77,'Shilo Sanders','','Football', 'Colorado','S','6''0"','195','GR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (78,'Will Lee III','','Football', 'Texas A&M','CB','6''2"','185','RJR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (79,'Malachi Moore','','Football', 'Alabama','S','6''0"','198','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (80,'Donovan Jackson','','Football', 'Ohio State','OG','6''4"','300','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (81,'Mitchell Evans','','Football', 'Notre Dame','TE','6''5"','260','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (82,'Zach Rice','','Football', 'North Carolina','OG','6''5"','315','RSO');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (83,'Donovan Edwards','','Football', 'Michigan','RB','6''0"','204','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (84,'Jamon Dumas-Johnson','','Football', 'Kentucky','ILB','6''1"','245','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (85,'Jeremiah Alexander','','Football', 'Alabama','EDGE','6''2"','249','RSO');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (86,'Shemar Turner','','Football', 'Texas A&M','DL3T','6''3"','300','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (87,'Bryce Foster','','Football', 'Kansas','OC','6''4"','325','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (88,'Tre Harris','','Football', 'Ole Miss','WR','6''2"','205','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (89,'Shavon Revel Jr.','','Football', 'East Carolina','CB','6''3"','200','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (90,'Cade Klubnik','','Football', 'Clemson','QB','6''2"','205','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (91,'Gentry Williams','','Football', 'Oklahoma','CB','6''0"','182','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (92,'Keon Sabb','','Football', 'Alabama','S','6''1"','208','RSO');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (93,'Jason Marshall Jr.','','Football', 'Florida','CB','6''0"','198','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (94,'Kevin Winston Jr.','','Football', 'Penn State','S','6''2"','204','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (95,'Ashton Jeanty','','Football', 'Boise State','RB','5''8"','210','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (96,'Jack Nelson','','Football', 'Wisconsin','OT','6''6"','310','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (97,'Earnest Greene III','','Football', 'Georgia','OG','6''4"','320','RSO');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (98,'Raheim Sanders','','Football', 'South Carolina','RB','6''1"','227','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (99,'Ashton Gillotte','','Football', 'Louisville','DL5T','6''3"','270','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (100,'Toriano Pride Jr.','','Football', 'Missouri','CB','5''11"','190','RJR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (101,'Dominic Lovett','','Football', 'Georgia','WRS','5''9"','185','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (102,'Caden Prieskorn','','Football', 'Ole Miss','TE','6''5"','255','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (103,'Tez Johnson','','Football', 'Oregon','WRS','5''10"','160','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (104,'Billy Bowman Jr.','','Football', 'Oklahoma','S','5''10"','190','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (105,'Clay Webb','','Football', 'Jacksonville State','OG','6''3"','290','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (106,'Jason Henderson','','Football', 'Old Dominion','ILB','6''1"','225','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (107,'Ajani Cornelius','','Football', 'Oregon','OT','6''4"','310','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (108,'T.J. Sanders','','Football', 'South Carolina','DL3T','6''5"','298','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (109,'Devon Jackson','','Football', 'Oregon','ILB','6''2"','228','RSO');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (110,'Omarion Hampton','','Football', 'North Carolina','RB','6''0"','220','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (111,'Antonio Williams','','Football', 'Clemson','WR','5''11"','195','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (112,'Akheem Mesidor','','Football', 'Miami (FL)','DL5T','6''2"','280','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (113,'Jalon Walker','','Football', 'Georgia','OLB','6''2"','245','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (114,'John Campbell Jr.','','Football', 'Tennessee','OT','6''5"','320','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (115,'Will Howard','','Football', 'Ohio State','QB','6''5"','242','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (116,'Jaydn Ott','','Football', 'California','RB','6''0"','200','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (117,'Daylen Everette','','Football', 'Georgia','CB','6''1"','190','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (118,'Mansoor Delane','','Football', 'Virginia Tech','CB','6''1"','182','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (119,'Cooper Mays','','Football', 'Tennessee','OC','6''2"','305','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (120,'Aeneas Peebles','','Football', 'Virginia Tech','DL5T','6''2"','280','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (121,'Thor Griffith','','Football', 'Louisville','DL3T','6''2"','305','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (122,'Marvin Jones Jr.','','Football', 'Florida State','EDGE','6''5"','250','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (123,'Benjamin Yurosek','','Football', 'Georgia','TE','6''4"','242','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (124,'Germie Bernard','','Football', 'Alabama','WR','6''1"','203','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (125,'Jordan Burch','','Football', 'Oregon','DL5T','6''5"','275','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (126,'Josh Conerly Jr.','','Football', 'Oregon','OT','6''4"','305','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (127,'Jordan Hancock','','Football', 'Ohio State','CB','6''1"','185','RJR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (128,'Joshua Gray','','Football', 'Oregon State','OT','6''4"','288','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (129,'J. Michael Sturdivant','','Football', 'UCLA','WR','6''2"','205','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (130,'Jo''Quavious Marks','','Football', 'USC','RB','5''10"','210','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (131,'Moose Muhammad III','','Football', 'Texas A&M','WR','6''1"','205','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (132,'Lathan Ransom','','Football', 'Ohio State','S','6''0"','207','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (133,'Hunter Wohler','','Football', 'Wisconsin','S','6''2"','211','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (134,'Seth McLaughlin','','Football', 'Ohio State','OC','6''4"','301','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (135,'Rylie Mills','','Football', 'Notre Dame','DL3T','6''5"','306','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (136,'Elic Ayomanor','','Football', 'Stanford','WR','6''2"','210','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (137,'Anthony Belton','','Football', 'NC State','OT','6''6"','336','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (138,'Jarquez Hunter','','Football', 'Auburn','RB','5''9"','202','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (139,'Aireontae Ersery','','Football', 'Minnesota','OT','6''5"','325','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (140,'Jake Briningstool','','Football', 'Clemson','TE','6''5"','230','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (141,'Nic Anderson','','Football', 'Oklahoma','WR','6''4"','209','RSO');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (142,'Darrell Jackson Jr.','','Football', 'Florida State','DL1T','6''5"','330','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (143,'Xavier Truss','','Football', 'Georgia','OT','6''6"','320','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (144,'Cameron Ward','','Football', 'Miami (FL)','QB','6''3"','220','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (145,'Kyren Lacy','','Football', 'LSU','WR','6''2"','215','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (146,'Alfred Collins','','Football', 'Texas','DL3T','6''4"','291','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (147,'Miles Frazier','','Football', 'LSU','OG','6''6"','335','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (148,'Nickolas Martin','','Football', 'Oklahoma State','ILB','6''0"','220','RJR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (149,'Xavier Watts','','Football', 'Notre Dame','S','6''0"','204','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (150,'Devin Neal','','Football', 'Kansas','RB','5''10"','210','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (151,'Logan Jones','','Football', 'Iowa','OC','6''3"','290','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (152,'Jaishawn Barham','','Football', 'Michigan','OLB','6''4"','233','RSO');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (153,'Derrick Moore','','Football', 'Michigan','EDGE','6''3"','258','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (154,'Caullin Lacy','','Football', 'Louisville','WRS','5''10"','190','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (155,'Ricky White III','','Football', 'UNLV','WR','6''1"','190','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (156,'Nolan Rucci','','Football', 'Penn State','OT','6''7"','305','RJR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (157,'Kamari Ramsey','','Football', 'USC','S','6''1"','205','RSO');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (158,'Jabbar Muhammad','','Football', 'Oregon','CBN','5''9"','183','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (159,'Riley Mahlman','','Football', 'Wisconsin','OT','6''8"','320','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (160,'Shemar James','','Football', 'Florida','ILB','6''1"','230','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (161,'Jahdae Barron','','Football', 'Texas','CB','5''11"','192','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (162,'Jay Higgins','','Football', 'Iowa','ILB','6''2"','233','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (163,'Bryson Nesbit','','Football', 'North Carolina','TE','6''5"','230','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (164,'Will Sheppard','','Football', 'Colorado','WR','6''3"','200','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (165,'Riley Leonard','','Football', 'Notre Dame','QB','6''4"','209','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (166,'Amari Jackson','','Football', 'Boston College','CB','5''10"','190','RJR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (167,'Jalon Daniels','','Football', 'Kansas','QB','6''0"','220','RJR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (168,'Oronde Gadsden II','','Football', 'Syracuse','WR','6''4"','216','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (169,'Aaron Graves','','Football', 'Iowa','DL3T','6''4"','293','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (170,'Connor Colby','','Football', 'Iowa','OG','6''5"','308','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (171,'Garrett Nussmeier','','Football', 'LSU','QB','6''2"','205','RJR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (172,'Jaeden Roberts','','Football', 'Alabama','OG','6''5"','316','RJR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (173,'Roman Hemby','','Football', 'Maryland','RB','6''0"','200','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (174,'Lander Barton','','Football', 'Utah','OLB','6''4"','242','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (175,'Trey Zuhn III','','Football', 'Texas A&M','OT','6''6"','315','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (176,'Jay Toia','','Football', 'UCLA','DL1T','6''2"','338','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (177,'Collin Oliver','','Football', 'Oklahoma State','OLB','6''2"','235','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (178,'Tyler Batty','','Football', 'BYU','DL5T','6''5"','273','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (179,'Jager Burton','','Football', 'Kentucky','OG','6''3"','307','RJR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (180,'Theo Wease Jr.','','Football', 'Missouri','WR','6''2"','200','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (181,'Quincy Riley','','Football', 'Louisville','CB','6''0"','185','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (182,'Marques Cox','','Football', 'Kentucky','OT','6''5"','311','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (183,'Tahj Brooks','','Football', 'Texas Tech','RB','5''10"','230','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (184,'Domonique Orange','','Football', 'Iowa State','DL1T','6''4"','335','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (185,'Xavier Restrepo','','Football', 'Miami (FL)','WRS','5''10"','198','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (186,'Deshawn Pace','','Football', 'Central Florida','OLB','6''2"','215','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (187,'Ricardo Hallman','','Football', 'Wisconsin','CBN','5''10"','185','RJR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (188,'Aubrey Burks','','Football', 'West Virginia','S','5''11"','202','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (189,'Khari Coleman','','Football', 'Ole Miss','OLB','6''1"','213','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (190,'Jamaree Caldwell','','Football', 'Oregon','DL1T','6''1"','320','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (191,'Jermayne Lole','','Football', 'Texas','DL1T','6''3"','315','GR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (192,'C.J. Dippre','','Football', 'Alabama','TE','6''4"','257','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (193,'Preston Stone','','Football', 'SMU','QB','6''1"','219','RJR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (194,'Squirrel White','','Football', 'Tennessee','WRS','5''9"','165','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (195,'Cobee Bryant','','Football', 'Kansas','CB','6''0"','175','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (196,'Jacob Parrish','','Football', 'Kansas State','CBN','5''10"','183','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (197,'Barion Brown','','Football', 'Kentucky','WR','6''1"','166','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (198,'Tyler Baron','','Football', 'Miami (FL)','EDGE','6''5"','260','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (199,'Eli Cox','','Football', 'Kentucky','OC','6''4"','311','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (200,'Tristan Leigh','','Football', 'Clemson','OT','6''6"','315','RJR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (201,'Yam Banks','','Football', 'Ole Miss','S','6''1"','208','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (202,'Caleb Ransaw','','Football', 'Tulane','CB','5''11"','194','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (203,'Josh Fryar','','Football', 'Ohio State','OT','6''6"','313','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (204,'Mason Taylor','','Football', 'LSU','TE','6''6"','255','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (205,'Jimmy Horn Jr.','','Football', 'Colorado','WRS','5''10"','170','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (206,'Kyle Monangai','','Football', 'Rutgers','RB','5''9"','210','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (207,'Dane Key','','Football', 'Kentucky','WR','6''2"','195','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (208,'Jalen Rivers','','Football', 'Miami (FL)','OG','6''5"','325','RJR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (209,'Deontae Lawson','','Football', 'Alabama','OLB','6''2"','230','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (210,'Davin Vann','','Football', 'NC State','DL5T','6''2"','280','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (211,'Reuben Fatheree II','','Football', 'Texas A&M','OT','6''7"','325','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (212,'C. J. Daniels','','Football', 'LSU','WR','6''1"','195','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (213,'Jacob Sexton','','Football', 'Oklahoma','OT','6''6"','325','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (214,'Tommi Hill','','Football', 'Nebraska','CB','6''0"','195','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (215,'K.C. Ossai','','Football', 'Louisiana','ILB','6''1"','244','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (216,'James Brockermeyer','','Football', 'TCU','OC','6''3"','285','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (217,'Tim Smith','','Football', 'Alabama','DL3T','6''3"','302','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (218,'Grayson McCall','','Football', 'NC State','QB','6''3"','210','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (219,'DeMonte Capehart','','Football', 'Clemson','DL3T','6''4"','320','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (220,'Damien Martinez','','Football', 'Miami (FL)','RB','5''11"','232','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (221,'Steve Linton','','Football', 'Baylor','EDGE','6''5"','235','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (222,'Noah Thomas','','Football', 'Texas A&M','WR','6''6"','200','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (223,'Cam Miller','','Football', 'Penn State','CB','6''0"','183','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (224,'Keionte Scott','','Football', 'Auburn','CBN','5''10"','186','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (225,'Dylan Fairchild','','Football', 'Georgia','OG','6''5"','315','RJR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (226,'Jasheen Davis','','Football', 'Wake Forest','EDGE','6''3"','260','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (227,'Gerald Mincey','','Football', 'Kentucky','OT','6''6"','337','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (228,'Will Rogers','','Football', 'Washington','QB','6''2"','215','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (229,'Jonathan Mendoza','','Football', 'Louisville','OT','6''8"','308','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (230,'Bru McCoy','','Football', 'Tennessee','WR','6''3"','220','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (231,'Colbie Young','','Football', 'Georgia','WR','6''4"','215','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (232,'Kemari Copeland','','Football', 'Virginia Tech','DL5T','6''3"','282','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (233,'Corey Thornton','','Football', 'Louisville','CB','6''1"','195','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (234,'Jalen Catalon','','Football', 'Texas','S','5''10"','201','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (235,'Josaiah Stewart','','Football', 'Michigan','EDGE','6''1"','237','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (236,'Peny Boone','','Football', 'UCF','RB','6''1"','242','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (237,'Deion Burks','','Football', 'Oklahoma','WRS','5''11"','180','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (238,'Akili Arnold','','Football', 'USC','S','6''0"','200','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (239,'Jake Johnson','','Football', 'North Carolina','TE','6''5"','240','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (240,'Tyler Van Dyke','','Football', 'Wisconsin','QB','6''4"','224','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (241,'Dorian Singer','','Football', 'Utah','WR','6''0"','180','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (242,'J.J. Pegues','','Football', 'Ole Miss','DL3T','6''2"','315','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (243,'Clarence Lewis','','Football', 'Syracuse','CB','5''11"','192','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (244,'Jalil Farooq','','Football', 'Oklahoma','WR','6''1"','204','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (245,'Keli Lawson','','Football', 'Virginia Tech','OLB','6''4"','223','RJR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (246,'Mario Williams','','Football', 'Tulane','WRS','5''9"','180','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (247,'Garrett Dellinger','','Football', 'LSU','OG','6''5"','325','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (248,'Jeremiah Cooper','','Football', 'Iowa State','S','6''0"','185','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (249,'Zion Nelson','','Football', 'Miami (FL)','OT','6''5"','316','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (250,'Zakhari Franklin','','Football', 'Illinois','WR','6''1"','190','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (251,'Tyreek Chappell','','Football', 'Texas A&M','CBN','5''10"','180','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (252,'Trevor Etienne','','Football', 'Georgia','RB','5''9"','205','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (253,'D.J. Uiagalelei','','Football', 'Florida State','QB','6''4"','235','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (254,'Fentrell Cypress II','','Football', 'Florida State','CBN','5''11"','182','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (255,'J.J. Weaver','','Football', 'Kentucky','EDGE','6''5"','244','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (256,'Damon Payne Jr.','','Football', 'Alabama','DL3T','6''3"','303','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (257,'Brandon Adams','','Football', 'UCF','CB','6''2"','186','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (258,'Kaimon Rucker','','Football', 'North Carolina','EDGE','6''2"','265','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (259,'Harold Fannin','','Football', 'Bowling Green','TE','6''4"','230','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (260,'J.C. Davis','','Football', 'Illinois','OT','6''5"','307','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (261,'Major Burns','','Football', 'LSU','S','6''2"','193','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (262,'Zy Alexander','','Football', 'LSU','CB','6''2"','188','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (263,'Cody Simon','','Football', 'Ohio State','OLB','6''2"','235','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (264,'J.Q. Hardaway','','Football', 'Kentucky','CB','6''2"','194','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (265,'Marcus Carroll','','Football', 'Missouri','RB','5''9"','210','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (266,'Marcus Tate','','Football', 'Clemson','OG','6''5"','325','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (267,'Nick Haberer','','Football', 'Washington State','P','6''5"','218','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (268,'Tony Grimes','','Football', 'UNLV','CB','6''0"','195','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (269,'Myles Purchase','','Football', 'Iowa State','CB','5''11"','205','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (270,'Walker Parks','','Football', 'Clemson','OG','6''5"','310','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (271,'Julian Fleming','','Football', 'Penn State','WR','6''2"','205','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (272,'Mello Dotson','','Football', 'Kansas','CB','6''0"','190','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (273,'Damonic Williams','','Football', 'Transfer','DL1T','6''2"','320','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (274,'Justin Walley','','Football', 'Minnesota','CB','5''11"','190','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (275,'Luke Kandra','','Football', 'Cincinnati','OG','6''4"','320','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (276,'Trey Moore','','Football', 'Texas','EDGE','6''3"','235','RJR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (277,'K.J. Jefferson','','Football', 'UCF','QB','6''3"','242','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (278,'Justus Ross-Simmons','','Football', 'Transfer','WR','6''3"','205','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (279,'Jaleel Skinner','','Football', 'Louisville','TE','6''5"','210','JR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (280,'Zemaiah Vaughn','','Football', 'Utah','CB','6''2"','185','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (281,'Quinn Schulte','','Football', 'Iowa','S','6''1"','209','GR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (282,'Gavin Bartholomew','','Football', 'Pittsburgh','TE','6''4"','255','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (283,'Devin Kirkwood','','Football', 'UCLA','CB','6''2"','208','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (284,'Jack Kiser','','Football', 'Notre Dame','OLB','6''2"','223','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (285,'Beaux Collins','','Football', 'Notre Dame','WR','6''2"','210','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (286,'Eugene Asante','','Football', 'Auburn','OLB','6''1"','222','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (287,'Alijah Huzzie','','Football', 'North Carolina','CBN','5''10"','195','GR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (288,'Daniel Jackson','','Football', 'Minnesota','WR','6''0"','200','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (289,'Robert Scott Jr.','','Football', 'Florida State','OT','6''5"','313','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (290,'Cam Jackson','','Football', 'Florida','DL1T','6''6"','360','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (291,'Jake Renfro','','Football', 'Wisconsin','OC','6''3"','310','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (292,'Tyler Warren','','Football', 'Penn State','TE','6''6"','257','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (293,'Bud Clark','','Football', 'TCU','S','6''2"','190','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (294,'Myles Hinton','','Football', 'Michigan','OT','6''6"','340','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (295,'Ja''Corey Brooks','','Football', 'Louisville','WR','6''2"','195','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (296,'Matthew Bedford','','Football', 'Oregon','OG','6''6"','305','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (297,'James Burnip','','Football', 'Alabama','P','6''6"','220','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (298,'Victor Stoffel','','Football', 'California','OT','6''7"','295','RSR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (299,'Eric Gentry','','Football', 'USC','OLB','6''5"','205','SR');
insert into player (id, first_name, last_name, sport,team,position,height,weight,year) values (300,'Denver Harris','','Football', 'UTSA','CB','6''0"','190','RSR');
